# Generated by Django 5.1.2 on 2024-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
